### ISSUE TITLE
Teensy 3.6 Support

### ISSUE THREAD

**Issue by phl0** [g4klx/MMDVM#43] opened 2016-11-28 19:58 UTC
I successfully compiled the MMDVM firmware for a Teensy 3.6 board. However starting MMDVMCal exits with exit code 1 and the MMDVM obviously stops running due to the LED on pin 13 not flashing any more.

![bildschirmfoto vom 2016-11-28 20-57-57](https://cloud.githubusercontent.com/assets/7112907/20683717/5de14738-b5ad-11e6-8913-a5aeb8ea2fa6.png)

![bildschirmfoto vom 2016-11-28 20-57-41](https://cloud.githubusercontent.com/assets/7112907/20683713/5a3f3978-b5ad-11e6-97c6-dc81968723fd.png)

It seems that the Teensy does not correctly answer to the writeConfig command.

**Comment by phl0** [comment] 2016-11-28 20:21
Tracking the issue further in the MMDVM firmware. Commenting out line 290 "io.start() does not stop the MMDVM from running for now.

**Comment by phl0** [comment] 2016-11-28 20:50
If I comment out the "Initialise ADC0" part, the else part in the "#if defined(EXTERNAL_OSC)" section and the "Initialise DAC" part the MMDVM firmware seems to start. Using MMDVMCal I can then toggle the PTT at least once.

**Comment by phl0** [comment] 2016-11-28 22:01
@g4klx: Just a dirty guess... According to https://forum.pjrc.com/archive/index.php/t-24492.html it says that waiting for calibration is:

```
// Begin calibration
ADC0_SC3 = ADC_SC3_CAL;
// Wait for calibration
while (ADC0_SC3 & ADC_SC3_CAL);
```

So maybe that " != ADC_SC3_CAL" appedix is needles?

**Comment by g4klx** [comment] 2016-11-29 07:04
They are functionally the same. Mine is more explicit.

**Comment by phl0** [comment] 2016-11-29 08:42
Interesting because if I omit the "!= ADC_SC3_CAL" the firmware executes beyond this point. Otherwise it hangs while executing this part ...

**Comment by g4klx** [comment] 2016-11-29 08:51
Oh! I stand corrected.

Where does it stop now?

**Comment by phl0** [comment] 2016-11-29 10:22
Tested with latest commit a40506aff0c577819ef9a8ac03c0f531d7503ffc:

- MMDVMCal starts correctly
- I can toggle PTT on and off using space

**Comment by phl0** [comment] 2016-11-29 12:35
Successfully also tested the RX Part of the MMDVM on Teensy 3.6. Connected it to my XLX reflector and made some test QSOs.

**Comment by phl0** [comment] 2016-11-29 14:26
MMDVM on Teensy 3.2 also working. 

![cyb26q5xcaab2da jpg large](https://cloud.githubusercontent.com/assets/7112907/20713319/2351ed84-b648-11e6-9877-ff7ec7ec2685.jpeg)

**Comment by phl0** [comment] 2016-11-29 14:42
Activating the external 12MHz TCXO in Config.h leads to MMDVMCal starting and beeing able to trigger the PTT once. There is no digital output on the TX NF line. After triggering the PTT once the MMDVM does not respond any more.

**Comment by phl0** [comment] 2016-11-30 07:17
Upgraded to 79440ca32df3ea8baa0f077dec3f458a9bf41479.
Compiled with 12 MHz TCXO enabled, connected LED to pin 3.
MMDVMCal can trigger the PTT only once, cannot de-key afterward. Pressing space multiple times gives:

![bildschirmfoto vom 2016-11-30 08-13-40](https://cloud.githubusercontent.com/assets/7112907/20743152/ebefe12e-b6d4-11e6-9c99-c7d528606eeb.png)

No TX Audio while keyed and RX audio not decoding.

Disabling TCXO makes it work again.

**Comment by N4IRS** [comment] 2016-12-12 15:35
I connected TCXO to pin 13 of the Teensy 3.6. Got the same PTT issues. I'm seeing the on board LED light when TCXO connected. I wonder if the LED and current limiting resistor is causing a problem. I am considering removing the LED to continue testing.

**Comment by g4klx** [comment] 2016-12-13 09:50
I asked on the Teensy forum and was given some feedback on what was wrong. I've updated my code, so if you can try it again and let me know what happens. I think you might be right about the LED, it's a shame that you can't use another pin for it.

**Comment by g4klx** [comment] 2016-12-14 09:18
Things have definitely moved on, but not quite correct yet it seems. Using the external TCXO, the settings for things like the ADC and DAC levels should be exactly the same as for using the internal clock except it should be better for DMR use. The LED should flash at the same rate in both modes for example.

I've done a tweak to the code which I hope makes the external TCXO match the internal oscillator even better. Please keep testing and report back any differences between the two modes.

I wonder if there's any mileage in making pin 3 the LED in both modes and abandon the mounted LED?

**Comment by g4klx** [comment] 2016-12-14 10:04
That sounds like good news. I won't declare it working until someone has had a DMR QSO with the TCXO enabled! We also need to look at the RSSI side (also on the STM32) to make sure that it's working.

**Comment by phl0** [comment] 2016-12-14 13:12
Jepp sure. I thought I should get the RF side up and running before looking at the RSSI stuff.
Is the RSSI stuff ok for testing? I saw that you committed to that part of the code before.

**Comment by g4klx** [comment] 2016-12-14 13:14
Concentrate on the TCXO side. The RSSI *should* work as-is once you define the requirement for RSSI in the Config.h. I want to create a 48 kHz version as soon as possible for the ZUM v1.2 boards. I wonder if someone will do a Teensy shield?

**Comment by g4klx** [comment] 2016-12-14 13:25
I've done a small change based on further feedback, this may be even better :-)

**Comment by N4IRS** [comment] 2016-12-14 13:32
I am not having any luck on receive of any mode. No decode with or without the TCXO. The same ZUM board and Due work properly. Since others are able to receive, I can only assume I have something wrong.
I did verify receiver audio to Pin 14 (A0). I will check the level and double check my other connections.

**Comment by phl0** [comment] 2016-12-14 13:41
@N4IRS Pin 14 (A0) is correct for RX NF. Correct pin on the Teensy board? Is it a 3.6 one?

**Comment by N4IRS** [comment] 2016-12-14 13:46
Yes, I'm going to get my 3.6 working before I try the 3.2. I will re-check everything again tonight.

**Comment by phl0** [comment] 2016-12-14 13:52
And you are using the ZUM 1.0 board? I could cross check that if you like.

**Comment by N4IRS** [comment] 2016-12-14 13:55
Yes it is a ZUM 1.0 audio board. Transmit audio works, PTT works and a quick check with a audio amp proves receive audio on pin 14. Tonight I'll check the level at pin 14. The way I built my test bed, I can unplug the ZUM from the Due and plug it into a breadboard with the 3.6.

**Comment by phl0** [comment] 2016-12-14 14:18
Ok, I wired up the ZUM v1.0 board to the Teensy. Aligning now ...

**Comment by phl0** [comment] 2016-12-14 14:28
Huh, confirmed that the Teensy will not receive anything with the ZUM v1.0 board ... *confused*

**Comment by N4IRS** [comment] 2016-12-14 14:29
OK, That is just strange. Filter values on the ZUM board? I did try the wide filter setting in config.h

**Comment by phl0** [comment] 2016-12-14 14:32
Dunno. Re-plugged v1.2 board and it receives .....

**Comment by N4IRS** [comment] 2016-12-14 14:38
Do you have a schematic of the 1.2 board so we can compare to the 1.0?

**Comment by N4IRS** [comment] 2016-12-14 14:39
Do we have confirmation of a 1.0 board working with the STM?

**Comment by g4klx** [comment] 2016-12-14 14:52
I'd love to know the difference. AFAIK they have wider filters on the ZUM 1.2 which is why I'm going to do a modern 48 kHz version so that the Nyquist frequency is 24 kHz instead of 12 kHz.

**Comment by N4IRS** [comment] 2016-12-14 14:55
I THINK the 1.2 board filters are based on the EB4FBZ filter design.

**Comment by phl0** [comment] 2016-12-14 14:56
Thats right.

**Comment by N4IRS** [comment] 2016-12-14 14:59
I know Colin was selling some boards in the UK, but he did not want to ship to the US. I would love to buy some of the "other" boards out there so I can test. So far I have been unsuccessful getting anyone to sell me a board.

**Comment by juribeparada** [comment] 2016-12-14 15:14
Hi guys, I would like to help, but I still waiting for my Teensy 3.6 arriving. Regarding STM, all my tests have been done with MMDVM 1.0 board, working OK. At the moment I don't have the 1.2 board.

**Comment by g4klx** [comment] 2016-12-14 15:33
They gut who helped me with the LPTMR posted the following. Anybody willing to try it out?

[GitHub](https://github.com/manitou48/teensy3/blob/master/adclptmr.ino)

I clocked pin13 from PWM pin 23 for testing.

FWIW, this may be circular nonsense, but with my sketch (PWM/23 to pin 13) @48khz (CMR 1), the long term LPTMR count shows an error of 24 ppm. I have measured the crystal on this T3.2 at about -19 ppm (with NTP or GPS), so that might? suggest the sketch/LPTMR is adding an error of 5 ppm? (48khz PWM is exact prescaler of 96mhz, so no discretization error). if i feed 48khz PWM into FreqCount library, it counts exactly 48000 for every 1s sample period... probably meaningless.

I obviously don't have a signal generator. If you feed your signal generator into my sketch, what does sketch report as measured frequency? and if you feed your generator into a FreqCount library sketch? 

or not.

**Comment by N4IRS** [comment] 2016-12-14 15:36
I'll try it tonight and report back.

**Comment by phl0** [comment] 2016-12-14 15:47
So what is the task? Testing the sketch above with the 12MHz TCXO of a MMDVM boards? That yields:

![bildschirmfoto vom 2016-12-14 16-43-06](https://cloud.githubusercontent.com/assets/7112907/21188841/f4c0d896-c21c-11e6-9e07-0683af3b5a8d.png)

**Comment by phl0** [comment] 2016-12-14 16:01
Also answered directly in the Teensy forum ;-)

**Comment by phl0** [comment] 2016-12-15 18:09
Tried manitou's sketch. Reports 17ppm ... Wierd .... Will try with the Teensy 3.2 and/or the ZUM 1.0 board

**Comment by phl0** [comment] 2016-12-15 22:48
Results are documented in the Teensy forum thread. Seems like we are measuring the drift of the Teensy's own crystal. Not sure if and how that affects the MMDVM's internals.

**Comment by g4eml** [comment] 2016-12-19 22:08
I have just got myself a Teensy 3.6. So far I am having the same problem where it doesn't appear to receive anything. The signal to A0 pin 14 looks fine on a scope and the level is well within the allowable range. I haven't connected up the TCXO yet and I am testing on both Dstar and DMR , neither shows any signs of receiving anything. Transmit is working fine so that indicates the interrupts must be firing at the correct rate (or close enough). I will do some more debugging to try to see what is happening. I can feel a lot of studying of the processor PDF document is going to be needed!

...Colin G4EML

**Comment by g4klx** [comment] 2016-12-20 08:48
That's interesting. I thought that Flo had it working fine on TX and RX a couple of weeks ago using the internal oscillator in D-Star mode. You are right about the interrupts though, the DAC is run off the ADC complete interrupt, which is hardware triggered off the timer. I also have a query about the RSSI ADC running, which is run from a software trigger on the signal ADC complete interrupt. but that can wait until later.

I get the feeling that it's almost there, but not quite. BTW I have pushed a small change to the calibration function based on feedback on the Teensy support forum which may help in some small way.

**Comment by phl0** [comment] 2016-12-20 08:50
Jonathan is right. At least with the internal oscillator (TCXO off) it
should work in D-Star more or less right away. I had that running a
while ago.

**Comment by g4klx** [comment] 2016-12-20 14:25
The Teensy RSSI input pin has changed. It turns out that ADC1 has only limited access to pins, and on the 3.1/3.2 they're only on the bottom side :-( The new mapping is: Teensy 3.5/3.6, A16, Pin 35. Teensy 3.1/3.2, A17, Pin 28. Please pass this information on to those that are testing it.

**Comment by g4eml** [comment] 2016-12-20 20:18
I modified teensyio.c so that the ADC values were immediately copied back out to the DAC and watched them on a scope. 
With noise on the Rx line the DAC signals were all max value (3.3V) with occasional spikes down to 1V.
I then fed in a variable DC voltage to the ADC and confirmed that the it appears to be working but with a reference voltage of about 1.2V instead of 3.3V. 
Any voltage above 1.2V  gives the 4095, the maximum reading.
As the centre point of the received audio is 1.65V then that would explain why my teensy is not receiving. 

I am now going back to the datasheet to try to see why this is happening. Maybe the internal reference voltage is programmable and has not been set up. 

Colin.

**Comment by g4eml** [comment] 2016-12-20 20:54
The reference for both ADC0 and ADC1 was set to internal. The internal reference for the chip is 1.2V as suspected.  On the Teensy the external reference pins are connected to 3V3 so the reference should be set to external.  I changed this in and now Dstar and DMR are both working on internal clock. 
Next to have a look at TCXO. 
Pull request submitted.

**Comment by g4eml** [comment] 2016-12-20 20:57
Maybe that's also the reason the ZUM Boards were showing different behaviors. If one had the DC offset of the output below 1.2V it would probably work.

**Comment by AllStarLink** [comment] 2016-12-20 20:58
I'll try it tonight.

**Comment by N4IRS** [comment] 2016-12-20 20:59
Let's try this again. ;)

I'll try it tonight.

**Comment by N4IRS** [comment] 2016-12-21 00:19
Did some very quick tests. D-Star receives, Fusion receives, P25 receives. I think DMR will receive once I re-set TX levels. This is with a Teensy 3.6 and a ZUM 1.0 board.

**Comment by N4IRS** [comment] 2016-12-21 01:06
Tested with 14 MHz TCXO. No transmit. Onboard LED stays "lit" Did not test receive. I hesitate to remove the LED but I may have to. Still, a LOT of progress tonight.

**Comment by g4klx** [comment] 2016-12-21 08:58
Thank you for your great input Colin. I've merged the changes, as well as porting them to the 48 kHz branch. I do have one query, there are warnings in the documentation about using the same reference for the DAC and ADC(s) at the same time with issues of crosstalk. Is that going to be an issue here?

**Comment by g4eml** [comment] 2016-12-21 17:31
Hi Jonathan, 

I don't think it will be an issue. Most processor documents I have seen before include a similar warning, generally they are only talking about very small interactions affecting the least significant bits. 

I will look at the external TCXO next to see if I can get that working.

I am also looking forward to trying the 48Khz branch again. I think with the extra processing power available it will be worth pursuing to improve the sampling point resolution.

**Comment by g4klx** [comment] 2016-12-21 20:04
The 48 kHz branch hasn't been tested and was put together quickly, so be careful with it. The levels are probably wrong at least :-(

**Comment by g4klx** [comment] 2016-12-22 15:39
Something work looking into in the future: getting ADC1 for RSSI to be run off the same hardware  interrupt as ADC0 to reduce the number of interrupts. This may give us a little more performance. It'd need to be done for both the PDB and LPTMR, but would bring the Teensy into line with the STM32 and the Due.

**Comment by g4eml** [comment] 2016-12-22 16:39
Tested with 14.4 Mhz TCXO. No ADC interrupts so no TX or Rx. 
Changed setting for ADC Pre-Trigger from B to A. (documentation is poor for this but I think A is correct for the way we are using it)
External TCXO now working. A 3 minute DMR transmission show no drift in the sample position as is correct. 
Pull Request submitted.

**Comment by g4eml** [comment] 2016-12-22 22:47
There is no need to make ADC1 use the PDB or LPTMR. 
Configure ADC1 as before but without enabling its interrupt. 
Every time ADC0 interrupts we read it and also read the previous conversion from ADC1. 
We then software trigger a new ADC1 conversion which will be available the next time ADC0 interrupts. 

I have tried this and it works fine as far as I can tell. 

Pull request created.

**Comment by N4IRS** [comment] 2016-12-23 00:57
Works well with the TCXO Transmit and receive on DMR and P25. Teensy 3.6.

**Comment by g4klx** [comment] 2016-12-23 08:46
The 48 kHz branch version of the Teensy is now out of date, could you do a similar pull request on that one too please.

**Comment by g4klx** [comment] 2016-12-24 10:28
I've updated the Teensy support on the 48 kHz branch to match the master branch apart from the sample rate.

**Comment by phl0** [comment] 2016-12-24 10:32
Been a little short in time the last days. Sorry. Great to see the Teensy working. Hope to find some spare time until new year to also test. Think I fried my MMDVM v1.0 :-( Maybe Santa brings a new one ... :-)

**Comment by g4eml** [comment] 2016-12-24 11:31
Thanks Jonathan, I was planning to do that today! 

I will try to get some time to test the 48Khz branch. 

Colin.

**Comment by N4IRS** [comment] 2016-12-24 11:51
I just did a quick test with the Teensy 3.2 without TCXO enable. Works on DMR without any changes to the level pots on the ZUM 1.0. More to follow.

Steve

**Comment by g4eml** [comment] 2016-12-24 20:46
48 Khz Branch tested on Teensy 3.6.  Works OK on DMR although no obvious improvement over 24Khz. 
Dstar receive appears to be OK but Dstar Transmit sounds wrong and is not decoded by radio. Tones sound too low in frequency. Not yet investigated. 
Merry Christmas.

**Comment by g4klx** [comment] 2016-12-25 00:04
It sounds like an oversight when translating the 24 kHz version. It'll be either the GMSK FIR coefficients, or the length/amplitude of 1/0 values. The 48 kHz version will come into its own with the ZUM 1.2 which uses the wider filters where the lower sample rate could cause aliasing issues.

Merry Christmas to you all.

**Closed** 2017-02-14 08:05 UTC
